#!/usr/bin/php

<?php

include ('conf_util.inc.php');

// téléchargement dans la base de données des comptes SIP + reconstitution
// du fichier de config

// the file generated by this script have to be included in original sip.conf
// of your asterisk server
conf_log(DEBUG_DEBUG, "Sip.conf...");

if (!false) // USE_SER
{
	$query = "Select VoIPAccount_ID, Name, FirstName, username, pwd, ".
			"VoIPAccount_People_Extension, canreinvite, host, ".
			"port, DtmfMode ".
		 "from People, Sip ".
		 "where extension = VoIPAccount_People_extension and enable = true";

	$query = $db->query($query);
	check_db($query);

	while ($row = $query->fetchRow(DB_FETCHMODE_ORDERED)) 
	{
		conf_log(DEBUG_DEBUG, '['.$row[3].'-'.$row[0].']');
		
		echo '['.$row[3].'-'.$row[0]."]\n";
		echo "context=obelisk-sip-pep\ntype=friend\n";
		if (is_null($row[7]))
			echo "host=dynamic\n";
		else
		{
			echo "host=".$row[7]."\n";
			if (!is_null($row[8]))
				echo "port=".$row[8]."\n";
		}
		echo 'callerid='.$row[2].' '.$row[1].' <'.$row[5]."> \n";
		echo 'canreinvite='.($row[6] ? "yes\n" : "no\n");
		echo 'secret='.$row[4]."\n";
		echo 'dtmfmode='.($row[9] == 1 ? "inband" : 
					($row[9] == 2 ? "rfc2833" : "info")).
					"\n\n";
	}
} else {
	// use ser, we just create a sip client without authentication from
	// the ip of the ser server
/*	echo '
[ser1]
host='.SER_IP.'
context=obelisk-sip-pep
type=friend
canreinvite=yes
'	;
}*/
	
	conf_log(DEBUG_CRIT, "not yet supported");
	
}
	conf_log(DEBUG_INFO, "DONE");

?>
