CREATE TABLE AgiInterface (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Sound_Outtro INTEGER UNSIGNED NOT NULL,
  Sound_Intro INTEGER UNSIGNED NOT NULL,
  Name VARCHAR(20) NOT NULL,
  LogIn BOOL NOT NULL,
  PRIMARY KEY(ID),
  INDEX AgiInterface_FKIndex1(Sound_Intro),
  INDEX AgiInterface_FKIndex2(Sound_Outtro)
);

CREATE TABLE AgiMenu (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Sound_After INTEGER UNSIGNED NULL,
  Sound_Announce INTEGER UNSIGNED NULL,
  Sound_Before INTEGER UNSIGNED NULL,
  Module_Action_ID INTEGER UNSIGNED NULL,
  Module_ID INTEGER UNSIGNED NULL,
  Parent INTEGER UNSIGNED NULL,
  AgiInterface_ID INTEGER UNSIGNED NOT NULL,
  Name VARCHAR(20) NOT NULL,
  Filename VARCHAR(20) NOT NULL,
  Action VARCHAR(10) NOT NULL,
  AccessMask VARCHAR(10) NOT NULL,
  PRIMARY KEY(ID),
  INDEX AgiMenu_FKIndex2(Parent),
  INDEX AgiMenu_FKIndex2(AgiInterface_ID),
  INDEX AgiMenu_FKIndex3(Module_ID, Module_Action_ID),
  INDEX AgiMenu_FKIndex4(Sound_Announce),
  INDEX AgiMenu_FKIndex5(Sound_Before),
  INDEX AgiMenu_FKIndex6(Sound_After)
);

CREATE TABLE AgiSound (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Filename VARCHAR(20) NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE AgiSound_Set (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  AgiSound_ID INTEGER UNSIGNED NOT NULL,
  Priority INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(ID),
  INDEX AgiSound_Set_FKIndex1(AgiSound_ID)
);

CREATE TABLE Extension (
  Extension INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Module_ID INTEGER UNSIGNED NOT NULL,
  ext_end INTEGER UNSIGNED NULL,
  PRIMARY KEY(Extension),
  INDEX extension_FKIndex1(Module_ID)
);

CREATE TABLE Geographical_alias (
  ext SMALLINT UNSIGNED NOT NULL,
  Geographical_Group_ID INTEGER UNSIGNED NOT NULL,
  People_ID INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(ext, Geographical_Group_ID),
  INDEX Geographical_alias_FKIndex1(Geographical_Group_ID)
);

CREATE TABLE Geographical_Group (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Name VARCHAR(32) NOT NULL,
  Len SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE Grp (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Name VARCHAR(32) NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE Grp_has_People (
  Grp_ID INTEGER UNSIGNED NOT NULL,
  People_ID INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(Grp_ID, People_ID),
  INDEX Groups_has_Peoples_FKIndex1(Grp_ID)
);

CREATE TABLE Iax (
  accountID DECIMAL(1,0) NOT NULL,
  People_ID INTEGER UNSIGNED NOT NULL,
  notransfer BOOL NOT NULL,
  host VARCHAR(50) NOT NULL,
  port SMALLINT UNSIGNED NULL,
  PRIMARY KEY(accountID, People_ID)
);

CREATE TABLE Module (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Name VARCHAR(20) NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE Module_Action (
  Module_ID INTEGER UNSIGNED NOT NULL,
  Action_ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Name VARCHAR(20) NULL,
  Description TEXT NULL,
  PRIMARY KEY(Module_ID, Action_ID),
  INDEX Module_Action_FKIndex1(Module_ID)
);

CREATE TABLE Network (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Name VARCHAR(64) NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE NetworkMask (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Network_ID INTEGER UNSIGNED NOT NULL,
  Mask VARCHAR(16) NOT NULL,
  PRIMARY KEY(ID, Network_ID),
  INDEX NetworkMask_FKIndex1(Network_ID)
);

CREATE TABLE NetworkProvider (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Name VARCHAR(32) NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE NetworkTimeZone (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  AsteriskDescString VARCHAR(64) NOT NULL,
  Name VARCHAR(32) NOT NULL,
  PRIMARY KEY(ID),
  UNIQUE INDEX NetworkTimeZone_Unique(Name)
);

CREATE TABLE People (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  username VARCHAR(32) NOT NULL,
  Name VARCHAR(48) NOT NULL,
  FirstName VARCHAR(48) NOT NULL,
  pwd INTEGER UNSIGNED NOT NULL,
  enable BOOL NOT NULL,
  mail VARCHAR(50) NOT NULL,
  PRIMARY KEY(ID),
  UNIQUE INDEX People_usernameUniq(username)
);

CREATE TABLE People_Settings (
  People_ID INTEGER UNSIGNED NOT NULL,
  credit DECIMAL(7,4) NOT NULL DEFAULT '0',
  announce DECIMAL(1) NOT NULL DEFAULT '1',
  ask_HigherCost BOOL NOT NULL,
  PRIMARY KEY(People_ID)
);

CREATE TABLE Price (
  Network_ID INTEGER UNSIGNED NOT NULL,
  NetworkProvider_ID INTEGER UNSIGNED NOT NULL,
  NetworkTimeZone_ID INTEGER UNSIGNED NOT NULL,
  Price DECIMAL(5,4) NOT NULL,
  ConnectionPrice DECIMAL(5,4) NOT NULL,
  PRIMARY KEY(Network_ID, NetworkProvider_ID, NetworkTimeZone_ID),
  INDEX Price_FKIndex1(Network_ID),
  INDEX Price_FKIndex2(NetworkProvider_ID),
  INDEX Price_FKIndex3(NetworkTimeZone_ID)
);

CREATE TABLE Rights (
  Grp_ID INTEGER UNSIGNED NOT NULL,
  Module_Action_ID INTEGER UNSIGNED NOT NULL,
  Module_ID INTEGER UNSIGNED NOT NULL,
  Value BOOL NOT NULL,
  PRIMARY KEY(Grp_ID, Module_Action_ID, Module_ID),
  INDEX Rights_FKIndex1(Grp_ID),
  INDEX Right_FKIndex2(Module_ID, Module_Action_ID)
);

CREATE TABLE Sip (
  accountID INTEGER UNSIGNED NOT NULL,
  People_ID INTEGER UNSIGNED NOT NULL,
  canreinvite BOOL NOT NULL,
  host VARCHAR(50) NULL,
  port SMALLINT UNSIGNED NULL,
  PRIMARY KEY(accountID, People_ID)
);

CREATE TABLE WebInterface (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Name VARCHAR(20) NOT NULL,
  ScreenName VARCHAR(40) NOT NULL,
  LogIn BOOL NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE WebMenu (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Module_Action_ID INTEGER UNSIGNED NOT NULL,
  Module_ID INTEGER UNSIGNED NOT NULL,
  Parent INTEGER UNSIGNED NULL,
  WebInterface_ID INTEGER UNSIGNED NOT NULL,
  Name VARCHAR(20) NOT NULL,
  ScreenName VARCHAR(40) NOT NULL,
  Filename VARCHAR(20) NOT NULL,
  Action VARCHAR(10) NOT NULL,
  PRIMARY KEY(ID),
  INDEX WebMenu_FKIndex2(Module_ID, Module_Action_ID),
  INDEX WebMenu_FKIndex3(WebInterface_ID),
  INDEX WebMenu_FKIndex3(Parent)
);


