CREATE TABLE Grp (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Name VARCHAR(32) NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE NetworkTimeZone (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  AsteriskDescString VARCHAR(64) NOT NULL,
  Name VARCHAR(32) NOT NULL,
  PRIMARY KEY(ID),
  UNIQUE INDEX NetworkTimeZone_Unique(Name)
);

CREATE TABLE Geographical_Group (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Parent INTEGER UNSIGNED NOT NULL,
  ext SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY(ID),
  INDEX Geographical_Group_FKIndex1(Parent),
  UNIQUE INDEX Geographical_Group_Uniq_ParentExt(Parent, ext),
  FOREIGN KEY(Parent)
    REFERENCES Geographical_Group(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE Network (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Name VARCHAR(64) NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE Module (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Name VARCHAR(20) NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE NetworkProvider (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Name VARCHAR(32) NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE AgiSound (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Filename VARCHAR(20) NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE WebInterface (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Name VARCHAR(20) NOT NULL,
  ScreenName VARCHAR(40) NOT NULL,
  LogIn BOOL NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE Dialplan (
  destination VARCHAR(20) NOT NULL AUTO_INCREMENT,
  source VARCHAR(20) NOT NULL,
  Action VARCHAR(512) NOT NULL,
  priority SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY(destination, source)
);

CREATE TABLE People (
  extension INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  pwd VARCHAR(32) NOT NULL,
  enable BOOL NOT NULL,
  mail VARCHAR(50) NOT NULL,
  PRIMARY KEY(extension)
);

CREATE TABLE Sip (
  accountID INTEGER UNSIGNED NOT NULL,
  People_extension INTEGER UNSIGNED NOT NULL,
  canreinvite BOOL NOT NULL,
  host VARCHAR(50) NOT NULL,
  port SMALLINT UNSIGNED NULL,
  PRIMARY KEY(accountID, People_extension),
  INDEX Sip_FKIndex1(People_extension),
  FOREIGN KEY(People_extension)
    REFERENCES People(extension)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE People_Settings (
  People_extension INTEGER UNSIGNED NOT NULL,
  credit DECIMAL(7,4) NOT NULL DEFAULT '0',
  announce DECIMAL(1) NOT NULL DEFAULT '1',
  ask_HigherCost BOOL NOT NULL,
  PRIMARY KEY(People_extension),
  INDEX People_Settings_FKIndex1(People_extension),
  FOREIGN KEY(People_extension)
    REFERENCES People(extension)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE NetworkMask (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Network_ID INTEGER UNSIGNED NOT NULL,
  Mask VARCHAR(16) NOT NULL,
  PRIMARY KEY(ID, Network_ID),
  INDEX NetworkMask_FKIndex1(Network_ID),
  FOREIGN KEY(Network_ID)
    REFERENCES Network(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE Module_Cron (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Module_ID INTEGER UNSIGNED NOT NULL,
  timerSec INTEGER UNSIGNED NOT NULL,
  filename VARCHAR(256) NOT NULL,
  PRIMARY KEY(ID, Module_ID),
  INDEX Module_Cron_FKIndex1(Module_ID),
  FOREIGN KEY(Module_ID)
    REFERENCES Module(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE Geographical_Group_Description (
  extension INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Geographical_Group_ID INTEGER UNSIGNED NOT NULL,
  Name VARCHAR(32) NOT NULL,
  Len SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY(extension),
  INDEX Geographical_Group_Description_FKIndex1(Geographical_Group_ID),
  FOREIGN KEY(Geographical_Group_ID)
    REFERENCES Geographical_Group(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE AgiSound_Set (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  AgiSound_ID INTEGER UNSIGNED NOT NULL,
  Priority INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(ID),
  INDEX AgiSound_Set_FKIndex1(AgiSound_ID),
  FOREIGN KEY(AgiSound_ID)
    REFERENCES AgiSound(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE Module_Action (
  Module_ID INTEGER UNSIGNED NOT NULL,
  Action_ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Name VARCHAR(20) NULL,
  Description TEXT NULL,
  PRIMARY KEY(Module_ID, Action_ID),
  INDEX Module_Action_FKIndex1(Module_ID),
  FOREIGN KEY(Module_ID)
    REFERENCES Module(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE Iax (
  accountID DECIMAL(1,0) NOT NULL,
  People_extension INTEGER UNSIGNED NOT NULL,
  notransfer BOOL NOT NULL,
  host VARCHAR(50) NOT NULL,
  port SMALLINT UNSIGNED NULL,
  PRIMARY KEY(accountID, People_extension),
  INDEX Iax_FKIndex1(People_extension),
  FOREIGN KEY(People_extension)
    REFERENCES People(extension)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE Rights (
  Grp_ID INTEGER UNSIGNED NOT NULL,
  Module_Action_ID INTEGER UNSIGNED NOT NULL,
  Module_ID INTEGER UNSIGNED NOT NULL,
  Value BOOL NOT NULL,
  PRIMARY KEY(Grp_ID, Module_Action_ID, Module_ID),
  INDEX Rights_FKIndex1(Grp_ID),
  INDEX Right_FKIndex2(Module_ID, Module_Action_ID),
  FOREIGN KEY(Grp_ID)
    REFERENCES Grp(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(Module_ID, Module_Action_ID)
    REFERENCES Module_Action(Module_ID, Action_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE AgiInterface (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Sound_Outtro INTEGER UNSIGNED NOT NULL,
  Sound_Intro INTEGER UNSIGNED NOT NULL,
  Name VARCHAR(20) NOT NULL,
  LogIn BOOL NOT NULL,
  PRIMARY KEY(ID),
  INDEX AgiInterface_FKIndex1(Sound_Intro),
  INDEX AgiInterface_FKIndex2(Sound_Outtro),
  FOREIGN KEY(Sound_Intro)
    REFERENCES AgiSound_Set(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(Sound_Outtro)
    REFERENCES AgiSound_Set(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE WebMenu (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Module_Action_ID INTEGER UNSIGNED NOT NULL,
  Module_ID INTEGER UNSIGNED NOT NULL,
  Parent INTEGER UNSIGNED NULL,
  WebInterface_ID INTEGER UNSIGNED NOT NULL,
  Name VARCHAR(20) NOT NULL,
  ScreenName VARCHAR(40) NOT NULL,
  Filename VARCHAR(20) NOT NULL,
  Action VARCHAR(10) NOT NULL,
  PRIMARY KEY(ID),
  INDEX WebMenu_FKIndex2(Module_ID, Module_Action_ID),
  INDEX WebMenu_FKIndex3(WebInterface_ID),
  INDEX WebMenu_FKIndex3(Parent),
  FOREIGN KEY(Module_ID, Module_Action_ID)
    REFERENCES Module_Action(Module_ID, Action_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(WebInterface_ID)
    REFERENCES WebInterface(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(Parent)
    REFERENCES WebMenu(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE Geographical_alias (
  Geographical_Group_ID INTEGER UNSIGNED NOT NULL,
  ext SMALLINT UNSIGNED NOT NULL,
  People_extension INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(Geographical_Group_ID, ext),
  INDEX Geographical_alias_FKIndex1(Geographical_Group_ID),
  INDEX Geographical_alias_FKIndex2(People_extension),
  FOREIGN KEY(Geographical_Group_ID)
    REFERENCES Geographical_Group(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(People_extension)
    REFERENCES People(extension)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE Grp_has_People (
  Grp_ID INTEGER UNSIGNED NOT NULL,
  People_extension INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(Grp_ID, People_extension),
  INDEX Groups_has_Peoples_FKIndex1(Grp_ID),
  INDEX Groups_has_Peoples_FKIndex2(People_extension),
  FOREIGN KEY(Grp_ID)
    REFERENCES Grp(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(People_extension)
    REFERENCES People(extension)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE Price (
  Network_ID INTEGER UNSIGNED NOT NULL,
  NetworkProvider_ID INTEGER UNSIGNED NOT NULL,
  NetworkTimeZone_ID INTEGER UNSIGNED NOT NULL,
  Price DECIMAL(5,4) NOT NULL,
  ConnectionPrice DECIMAL(5,4) NOT NULL,
  PRIMARY KEY(Network_ID, NetworkProvider_ID, NetworkTimeZone_ID),
  INDEX Price_FKIndex1(Network_ID),
  INDEX Price_FKIndex2(NetworkProvider_ID),
  INDEX Price_FKIndex3(NetworkTimeZone_ID),
  FOREIGN KEY(Network_ID)
    REFERENCES Network(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(NetworkProvider_ID)
    REFERENCES NetworkProvider(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(NetworkTimeZone_ID)
    REFERENCES NetworkTimeZone(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE AgiMenu (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Sound_After INTEGER UNSIGNED NULL,
  Sound_Announce INTEGER UNSIGNED NULL,
  Sound_Before INTEGER UNSIGNED NULL,
  Module_Action_ID INTEGER UNSIGNED NULL,
  Module_ID INTEGER UNSIGNED NULL,
  Parent INTEGER UNSIGNED NULL,
  AgiInterface_ID INTEGER UNSIGNED NOT NULL,
  Name VARCHAR(20) NOT NULL,
  Filename VARCHAR(20) NOT NULL,
  Action VARCHAR(10) NOT NULL,
  AccessMask VARCHAR(10) NOT NULL,
  PRIMARY KEY(ID),
  INDEX AgiMenu_FKIndex2(Parent),
  INDEX AgiMenu_FKIndex2(AgiInterface_ID),
  INDEX AgiMenu_FKIndex3(Module_ID, Module_Action_ID),
  INDEX AgiMenu_FKIndex4(Sound_Announce),
  INDEX AgiMenu_FKIndex5(Sound_Before),
  INDEX AgiMenu_FKIndex6(Sound_After),
  FOREIGN KEY(Parent)
    REFERENCES AgiMenu(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(AgiInterface_ID)
    REFERENCES AgiInterface(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(Module_ID, Module_Action_ID)
    REFERENCES Module_Action(Module_ID, Action_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(Sound_Announce)
    REFERENCES AgiSound_Set(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(Sound_Before)
    REFERENCES AgiSound_Set(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(Sound_After)
    REFERENCES AgiSound_Set(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);


